spring:
  application:
    name: Authorization Service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: password
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: off
server:
  port: 9000

token:
  access-token-ttl: 300
  refresh-token-ttl: 2592000
  authorization-code-ttl: 300


auth:
  allowed-scopes: openid, profile, email, phone, address, read, write
  allowed-grant-types: authorization_code, refresh_token, client_credentials
client:
  require-proof-key: false
  require-authorization-consent: false